spring:
  application:
    name: demo
  # 数据源配置
  datasource:
    url: jdbc:mysql://10.10.14.39:6603/test11?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: cjian3 # 你的MySQL用户名
    password: cjian@123456 # 你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL8.x驱动（5.x用 com.mysql.jdbc.Dr
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.demo
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
